### ISSUE TITLE
New design for Ratings card

### ISSUE THREAD

**Issue by rkzack** [ournews/extensions#17]
Hi @webcolor-in could you please style the Ratings card to look more like this?

![image](https://user-images.githubusercontent.com/35204816/65924582-6dadb180-e3bb-11e9-9bc0-8f14c9246dd3.png)

**Comment by webcolor-in** [comment]
Yes, can do it. So this should be new requirement? Estimated effort?

**Comment by rkzack** [comment]
Yes new requirement. What do you think estimated time will be?

**Comment by webcolor-in** [comment]
Considering there will be lot of code clean in this view apart from building new one my estimate is around 30 hours, can deliver by Saturday. If that is good you can share API that will be used, GET/POST key/value pairs expected.

**Comment by webcolor-in** [comment]
Should we change the QA view to follow similar selection highlight style as above so they are consistent? I can add that change if needed.

**Comment by rkzack** [comment]
Yes. But please fix issues in other ticket first before doing this work, that's highest priority so we can get the new release out asap. The ratings card design is meant to be second phase.

**Comment by webcolor-in** [comment]
Have fixed issues and code pushed to remote. Let me know when I can start with this one like today tomorrow or some other day.

**Comment by webcolor-in** [comment]
**[Move to IFrame & Vue.js based views]** 

My observation is we do not use or modify anything in the page where extension is loaded so I was thinking instead of injecting all our HTML in page we can choose to inject IFrame and render everything within IFrame. All we are doing from current loaded page is using the URL for validation and data fetch from backend API and this can be done inside IFrame with some checks.

The reason why I am recommending this approach is: 
- Website CSS/JS will not interfere with extension
- Code improvement - We can use Vue.js that provides view template + data binding so we can write more business logic than DOM handling code. This will clean up lots of JS code and jQuery dependency. 
- Easy to understand and change - Using Vue.js makes it easy to understand and change code.
- Less bugs & more stable product - No DOM handling code removes won't exist giving us more stable product.

This requires good effort plus I don't recommend doing when we are building feature actively but something that I can take up once you/your team agrees.

**Comment by webcolor-in** [comment]
Also I will wait for your message to start on ratings redesign.

**Comment by rkzack** [comment]
Thank you. We think the estimate of 30 hours seems a little high, since it's just redesigning the buttons and layout on one card. There's no other major functionality changes here, and no changes to the API calls (just a few extra buttons but they all POST the same way). Can you try to see if you can get the changes done in 20 hours?  If so, we can approve this right away.

**Comment by webcolor-in** [comment]
Sure, lets go with same then. There was some code clean up and rearrangement that I had thought at that time but I think removing unwanted code and adding new feature should be good enough. Please share API GET/POST details and I will get started on this. Time wise I will deliver by Monday.

**Comment by rkzack** [comment]
Ok sure. The API GET/POST details are the same as they are currently on the card. The only difference is the value to post with as `quicktype` along with the `quicknid` value. 

Here's the list for all the option buttons, from left to right:

Spin --  biasleft, biasleanleft, nobias, biasleanright, biasright

Trust -- mistrust, trust2, trust3, trust4, trust

Accuracy -- reject, accuracy2, accuracy3, accuracy4, accept

Relevance -- real (#News), opinion (#Opinion), bait (#Clickbait), satire (#Satire), misleading (#Misleading),  other (#other).

**Comment by webcolor-in** [comment]
What about the top raters?

**Comment by rkzack** [comment]
That info and functionality is already present in the older version of the extension under the Ratings card, please see that for reference. All that's changing is moving that to this card, and changing the formatting to the new design. The top raters should only be displayed to logged in users, and the data comes from the `exturlprivatenid` call, the `results.raters` array.

**Comment by rkzack** [comment]
Ok that's added to the `results.raters` array -- `profileimage`

**Comment by webcolor-in** [comment]
![Annotation 2019-10-06 204938](https://user-images.githubusercontent.com/55145799/66271376-da70f200-e87a-11e9-9131-09b15f0ecfe6.png)
Does this option label look right? especially for spin.

**Comment by webcolor-in** [comment]
Plus, what should go in results for each? API for that?

**Comment by rkzack** [comment]
Can you please make it look more like the design?

**Comment by rkzack** [comment]
Also, the results are within the `exturlprivatenid` call, in the `results.mine.quicks` array

**Comment by webcolor-in** [comment]
Not my answers but results? I see in screenshot you have written "Results:" under each questions, that one.

UI - Yes it will look like mockup, I was sharing to confirm labels.

**Comment by rkzack** [comment]
Ok look in the results.ratings array

**Comment by webcolor-in** [comment]
![Annotation 2019-10-07 130141](https://user-images.githubusercontent.com/55145799/66292739-a17c6000-e902-11e9-8341-68b2535a41af.png)
I was asking for this result, it has count within bracket

**Comment by rkzack** [comment]
The count is the totalratings value which will be the same number for each result on this page. The rest of the results are in the array I mentioned. This is exactly the same data and how it worked before on the ratings card. Try looking at the JSON results carefully, you will see all the data you need is there.

**Comment by webcolor-in** [comment]
Let me explain, mockup screenshot is bit blurry so let me put the results text that I understand, correct me if I am wrong.

Result: No Spin (500 Ratings)
Result: 5 - Very Trustworthy (500 Ratings)
Result: 4 - Accurate (500 Ratings)
Result: 100% News (500 Ratings)

API give me ratings which is like this:
`ratings: {
accuracy: "93.03"
quality: "90.0311"
relevance: "News"
relevancelabel: "Certain"
relevancevalue: "100"
spin: "Left"
spinvalue: 47.9
total: "11"
trust: "93.03"}`

From this I can get spin label, spin value and relevance label, relevance value. What about trust and accuracy? they come as percentage and there is no label.

**Comment by rkzack** [comment]
Ok, thank you for clarifying. You should now see two more values in `results.ratings` array: 

`trustlabel` and `accuracylabel`

**Comment by webcolor-in** [comment]
![Annotation 2019-10-09 202345](https://user-images.githubusercontent.com/55145799/66492862-b576bc00-ead2-11e9-8ddf-0b37c42930f1.png)
Do you see your twitter page like this? left side icons arranged top to bottom?

**Comment by webcolor-in** [comment]
Result is updated, code pushed.

**Comment by rkzack** [comment]
Thanks!  Looks good so far, but a few issues to address:

- [ ] For Spin -- please change the buttons to be all on one-line, with this wording:

[Left] [Lean Left] [None] [Lean Right] [Right]

- [ ]  For Trust and Accuracy, the printed values on the buttons should be:  1, 2, 3, 4, 5 -- not 0, 1, 2, 3, 4 as they are now

- [ ] For Relevance -- it's missing an option--  `#Other` 

- [ ] For Relevance -- can you make the design match exactly to the mockup we provided?

- [ ] For Relevance -- only show the first two digits of the score, nothing after the decimal point, for example instead of `99.86%` it should only show `99%`

- [ ] For all of these metrics -- remove the count of ratings number from the Results   -- ie [17 Ratings] -- this should just now look something like:  Results: [90% - Very High]

**Comment by webcolor-in** [comment]
All fixed and code pushed

**Comment by rkzack** [comment]
Thank you. A few more issues discovered:

- [ ]  Please do not commit any changes directly to the master branch, changes should always be committed to separate branches, or create a new branch. 

- [ ]  On the Fact-Check card, bug, the Top Indicators section is now always blank (see screenshot) 

<img width="388" alt="2019-10-11_1004" src="https://user-images.githubusercontent.com/35204816/66658029-a9901480-ec0e-11e9-80dd-de33d74e7909.png">

- [ ]  Also on the Fact-Check card, change the words "Newstrition Label" to be "Publisher Profile"

- [ ]  On the Ratings card, for Accuracy and Trust -- only show the first two digits of the score, nothing after the decimal point, for example instead of `16.52%` it should only show `16%`

- [ ]  Same for all the results with the questions at the top-- only show the first two digits of the scores. 

- [ ]  On the Ratings card, for Relevance -- the Results display is missing the `relevance` value-- and we no longer want to display the exact score for Relevance. So it should display like:  

Results:  #News [Certain] --   ie.  Results:  #`results.ratings.ratings.relevance` [`results.ratings.ratings.relevancelabel`]

**Comment by webcolor-in** [comment]
All done and code pushed

**Comment by webcolor-in** [comment]
Let me check on top indicators, guess there was no value there.

**Comment by webcolor-in** [comment]
Top indicators - Fixed and pushed

**Comment by webcolor-in** [comment]
"Please do not commit any changes directly to the master branch, changes should always be committed to separate branches, or create a new branch."

There is nothing I commit or push to main branch, its always -  **satya-sept-19**

**Comment by rkzack** [comment]
Ok, thank you, those all look good.  We made a few other design tweaks and committed them to `satya-sept-19` branch, please grab the latest, and then look at two more issues:

- [ ]  is it possible to make the extension always grab a new `exturlprivate` result immediately after each rating is placed on the ratings card?  otherwise it takes 10 seconds to show the results of a user ratings, and users might wonder if their rating was actually counted

- [ ] on the Fact-Check card, when clicking on one of the Article Sources, it is properly posting a tracking `sourceclick`, however, this doesn't appear to be happening for any of the sources under the User Contributed Sources section. Can you please make it do so there as well?

**Comment by webcolor-in** [comment]
Both issues fixed, code pushed. I added data refresh after user does rating and answers any question.

**Comment by rkzack** [comment]
Hmm, ok that's working, but now a new issue--- it looks like the question sequence gets reset at the top upon refresh-- so every time you answer a question, now its refreshing and taking you back to the first question. The refresh shouldn't reset the question sequence.

**Comment by webcolor-in** [comment]
Should I remove the refresh for QA alone then? Because its bit complex to deal above situation.. basically when answer set changes it refreshes entire QA set otherwise it does not. And QA set can be modified either by answering or from quick ratings.

**Comment by rkzack** [comment]
Yes, for now, just remove refresh for the top questions/answers.  For the next revision, we will need a better way to deal with the above situation. Thank you.

**Comment by webcolor-in** [comment]
Have updated and code pushed, will find some better way to solve this and put in future release.

**Comment by rkzack** [comment]
The latest fix doesn't seem to work for me. It is still refreshing the top questions after each rating. I think the way to fix this is to (1) not display any individual question in the top part if someone has already answered that question; and (2) not refresh the top questions part at all during any refresh.

**Comment by webcolor-in** [comment]
1. It will refresh immediately if after clicking any quick rating
2. It will not refresh immediately after clicking any QA (top) - Same as before

I found a new logic that will be added in next version:
Top QA - To update questions only if they are different or to update only answers without resetting questions

**Comment by rkzack** [comment]
This is not working:  Yes, for now, just remove refresh for the top questions/answers.

Please entirely remove the refresh for the top questions/answers in all cases for now.

**Comment by webcolor-in** [comment]
Immediate refresh after quick ratings is removed now.

**Comment by webcolor-in** [comment]
@rkzack New logic to not reset layout and just updated answers plus immediate refresh after quick rating and answer is complete, code pushed.

**Comment by rkzack** [comment]
This looks good, thank you. Closing issue.
