### ISSUE TITLE
Problems with extension when not logged in

### ISSUE THREAD

**Issue by rkzack** [ournews/extensions#19]
@webcolor-in we've discovered serious issues in the extensions, when a user is not logged in. We've been planning a rollout for tomorrow morning our time. Can you please fix asap?

Testing using this url:  `http://actionnews3.com/rat-meat-has-been-sold-as-chicken-wings/`

- When not logged in, nothing ever loads, it just shows:

![Screen Shot 2019-10-04 at 6 42 03 PM](https://user-images.githubusercontent.com/35204816/66244494-b2488e00-e6d6-11e9-9cf8-882a831740d6.png)

- Even if not logged in, it should still show the questions. If someone tries to answer, it should popup the box letting them know they need to either login or register

- Also, the header links to Login and Register don't seem to work-- they should point to:

Login:  https://our.news/wp-login.php/?CID=ON.Chrome
Register:  https://our.news/register/?CID=ON.Chrome

**Comment by webcolor-in** [comment]
I just checked and it failed due to some other reason, its checking for mine.answer everytime even if user is not logged in so I add extra checks here which should fix this. 

Also, the header links to Login and Register don't seem to work-- I thought its expected similar to welcome or hi message but can be changed easily, let me update this one too.

**Comment by webcolor-in** [comment]
First 2 issues fixed, working on second one

**Comment by webcolor-in** [comment]
This is the URL that iframe hits for login - 
https://our.news/wp-login.php?extension=1&CID=ON.Chrome&redirect_to=https://our.news/extension/view.php
https://our.news/wp-login.php?extension=1&CID=ON.Firefox&redirect_to=https://our.news/extension/view.php

**Comment by rkzack** [comment]
RE URL ok that's right

**Comment by webcolor-in** [comment]
Third issues is also fixed, code pushed

**Comment by rkzack** [comment]
Thank you testing now. One more issue, sorry, on laptops the height of the extension is too high, and content is cut off at the bottom. Can a scrollbar be added so a user could scroll down?

**Comment by webcolor-in** [comment]
I was thinking about adding scrollbar after summary page came in but then it shouldn't up when user screen has available height so let me add this check along.

**Comment by webcolor-in** [comment]
![Annotation 2019-10-05 071122](https://user-images.githubusercontent.com/55145799/66247997-5b2ad380-e73f-11e9-99a6-abd54b0687a5.png)
How about adding just to summary view? Adding to entire popup doesn't look right because other tabs don't have large height.

**Comment by rkzack** [comment]
I like where you put the scrollbar but all the tabs (Newstrition, Fact-Check, Ratings) get cutoff for me on my laptop... 

<img width="403" alt="Screen Shot 2019-10-04 at 9 44 17 PM" src="https://user-images.githubusercontent.com/35204816/66248031-2cd1d780-e6f0-11e9-84d0-1ffb939cc3fd.png">

**Comment by webcolor-in** [comment]
I think QA is adding more height so all tabs look cropped, let me add scrollbar just for tabs. Is that okay?

**Comment by rkzack** [comment]
yes

**Comment by webcolor-in** [comment]
done & pushed
