### ISSUE TITLE
Notification red circle gets sized improperly on certain URLs

### ISSUE THREAD

**Issue by rkzack** [ournews/extensions#2]
In the top header of the extension modal there's a red circle which shows the logged-in user's notification count. However, on some sites, the size of the red circle changes to something other than what we've set, and is either too large or too small. The size should always be consistent.

For example URL:

https://ascienceenthusiast.com/trump-taps-ancient-aliens-guy-secretary-space-force/

**Comment by rkzack** [comment]
@webcolor-in want to take a look at this too?

**Comment by webcolor-in** [comment]
Will check and fix it now

**Comment by webcolor-in** [comment]
changes done, code pushed
