### ISSUE TITLE
Twitter functionality no longer working

### ISSUE THREAD

**Issue by rkzack** [ournews/extensions#21]
Hi @webcolor-in it looks like the extension no longer works with Twitter (both the old and new versions). This must be a recent change with Twitter. Can you please investigate asap?

**Comment by webcolor-in** [comment]
![Annotation 2019-10-05 191441](https://user-images.githubusercontent.com/55145799/66255708-767bfa00-e7a4-11e9-8e62-1598e9fb9ea0.png)
I tested ON-Chrome build and its working good in my machine. I didn't test the old version of extension yet. 

So if you tell me what error do you see like
1. Little icon in tweet does not appear?
2. After icon click it doesn't open popup? 
3. After open it doesn't do anything?
Just a little more info so I can reproduce at my end.

**Comment by rkzack** [comment]
1. The little icon never appears

**Comment by webcolor-in** [comment]
Can you send me screenshot of console tab (chrome developer tool)? there should be error thrown there if something has gone wrong. Meantime I will try in other machines.

**Comment by rkzack** [comment]
Nothing in the console tab....

**Comment by rkzack** [comment]
We've tried it from four different machines, both firefox and chrome, and it doesn't seem to work with Twitter anymore. All the latest browser versions. The little icon never appears in any tweets. Have you been able to find anything?

**Comment by webcolor-in** [comment]
No, I didn't find anything yet. Checking with other machines now.

**Comment by webcolor-in** [comment]
I tested another machine and it worked in both Chrome & Firefox.. it was windows. Are you testing it on mac or windows?

**Comment by rkzack** [comment]
Testing on mac..

**Comment by webcolor-in** [comment]
![Annotation 2019-10-05 213557](https://user-images.githubusercontent.com/55145799/66257593-bc42bd80-e7b8-11e9-8bc7-1051b4a65e8e.png)
At my end its working even in mac but only after 2/3 times page refresh after fresh install from store, strange... let me test in more machines.

**Comment by webcolor-in** [comment]
All that extension does for injecting this tiny icon is check for
$(".js-stream-item") which is twitter post (<li>)

**Comment by rkzack** [comment]
This is still an issue for us, were you able to resolve this?

**Comment by webcolor-in** [comment]
I couldn't reproduce this. It worked in mac machine that I have so I started testing in https://live.browserstack.com with different versions of mac + chrome 76 and its working there as well. I installed the latest you uploaded in chrome store. So may be its just your machine that has trouble? or you have both of our extensions and there is any issue at that time?

**Comment by rkzack** [comment]
We have tested this now with six different machines both Firefox and Chrome. It does not work on any machine with either browser. Please fix, we cannot release this new version with it broken. Thank you.

**Comment by webcolor-in** [comment]
I can fix once I know the issue but I am not able to reproduce so I am stuck. I tested with https://live.browserstack.com which offer several OS and Chrome/FF versions and its working in all versions. You said its happening even with older version of extension which means some selector in twitter page is changed and it could be that the version shown in US is different, I am not sure. If I get to see source code of twitter shown in devices where extension is failing I can nail it down.

**Comment by rkzack** [comment]
Can we schedule a remote shared screen session where you remotely see this happening on one of my machines and can then look at the source code?  I am available for the next 1-2 hours.

**Comment by rkzack** [comment]
Or, here is attached a copy of the view-source for twitter.com. 

[twitter.txt](https://github.com/ournews/extensions/files/3707447/twitter.txt)

**Comment by webcolor-in** [comment]
Yes, I am ready for that. Let me know what I need to install or you can also attach source code if possible.

**Comment by rkzack** [comment]
Ok, I attached the source code, let me know if we still need to do remote share.

**Comment by webcolor-in** [comment]
This is view->source which gets executed and brings more stuffs after loading in screen. What will be useful is sending the live source code that is shown after page load. You can copy that from Chrome developer tools.

**Comment by rkzack** [comment]
You'll need to send me step by step instructions then, all I see is View->Developer->View Source.

**Comment by webcolor-in** [comment]
![Annotation 2019-10-09 183817](https://user-images.githubusercontent.com/55145799/66484101-fc10ea00-eac3-11e9-8058-5de4cc4799e7.png)

**Comment by webcolor-in** [comment]
Paste that in txt file and attach, that's it.

**Comment by rkzack** [comment]
[twitter2.txt](https://github.com/ournews/extensions/files/3707468/twitter2.txt)

**Comment by webcolor-in** [comment]
![Annotation 2019-10-09 202345](https://user-images.githubusercontent.com/55145799/66492918-ce7f6d00-ead2-11e9-862e-d3f014ba207d.png)
Do you see icons arranged like this in vertical fashion in your mac? ignore right side sorry text.

**Comment by rkzack** [comment]
Here's a screenshot
<img width="1279" alt="Screen Shot 2019-10-09 at 10 54 55 AM" src="https://user-images.githubusercontent.com/35204816/66493019-59387b80-ea83-11e9-8cef-cf1354cd257f.png">

**Comment by webcolor-in** [comment]
Got it, actually that's twitter's mobile version of page. For example if we hit https://mobile.twitter.com/ we will see same version & style. Since our extension does not check mobile version of twitter code it isn't showing any icon. What is not clear is why you are shown mobile version of twitter or twitter made this change recently.

**Comment by rkzack** [comment]
Ok understood, glad you figured that out. Yea I am not sure why it shows that either, but thats what we see on all machines from all accounts. Can you fix?

**Comment by rkzack** [comment]
Ok but the issue happens on all computers so we do consider this a critical flaw that is preventing the launch of our extension. The screen shot that I showed you was from a 27" iMac.  https://www.apple.com/shop/buy-mac/imac/27-inch-3.0ghz-6-core-processor-with-turbo-boost-up-to-4.1ghz-1tb

We've tested in Windows desktops as well. Only one laptop was tested and it doesn't work there either. The issue happens on every computer, so we have to get this fixed asap.

14-15 hours is approved.

**Comment by webcolor-in** [comment]
Understood, this means twitter is rolling out mobile version to desktop mode atleast in US for sure. I will start working on this one now.

**Comment by webcolor-in** [comment]
I was wrong with estimates, these guys have updated twitter page to react.js based views which means the page is more dynamic and does not have easy selectors like before (same as facebook) plus it keeps refreshing every element every moment. I can complete by Sun. and it will take me ~25 hours.

**Comment by webcolor-in** [comment]
@rkzack - Waiting for your approval

**Comment by rkzack** [comment]
Approved

**Comment by webcolor-in** [comment]
@rkzack - I can add something that this extension has and show old twitter layout., this is simple and easy way. Their new page style is designed to prevent bots so hardly any relevant selectors making it hard.

https://chrome.google.com/webstore/detail/goodtwitter/jbanhionoclikdjnjlcmefiofgjimgca?hl=en

**Comment by webcolor-in** [comment]
Have updated extension to detect Twitter page if its old layout or new one and add our.news icon accordingly. Twitter's new layout has fully obfuscated css making it super hard to write selectors so 
- There is no way to identify if a post belong to timeline or is a comment vs standard post
- I add ON icon if a tweet has external link to article otherwise it won't add any icon

I updated version and pushed my code

**Comment by rkzack** [comment]
Ok thank you. I just tested this and the approach should be ok. Just one major issue so far (on Twitter), is that it's always incorrectly passing the ?pub variable. It looks like it's always requesting the current username. See log file example:

`67.242.87.170 - - [13/Oct/2019:09:14:30 -0400] "GET /api/?pub=richardkzack&_=1570971456965 HTTP/1.0" 200 845 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36"`

We have a very specific way we want you to fix this, as this brings up something else that we need to change which will provide more accurate data. While we identified this issue due to Twitter, please make this change for all sites, as it should be less complicated and more accurate.

Currently, the extension grabs the publisher information (on Newstrition card) from the `pub` endpoint, with an interpreted domain name as a variable. Instead of doing this, please change it so that it grabs the publisher information from the `publink` endpoint, that it gets from just passing the current link it's on. So no interpretation necessary anymore.

A few examples:

Link:  `https://slate.com/news-and-politics/2019/10/trump-defends-giuliani-reports-criminal-investigation.html`
Previous call:  `/api/?pub=slate.com`
New call:  `/api/?publink=https://slate.com/news-and-politics/2019/10/trump-defends-giuliani-reports-criminal-investigation.html`

Link:  `https://twitter.com/TheRickWilson/status/1183367552640126976`
Previous call:  `/api/?pub=twitter.com/TheRickWilson`
New call:  `/api/?publink=https://twitter.com/TheRickWilson/status/1183367552640126976`

The `?publink` API endpoint will return the exact structure of data as the `?pub` endpoint, it just expects the actual link, instead of the publisher domain. Thank you.

**Comment by webcolor-in** [comment]
Fixed - picking right pub starting with '@' and code pushed.

**Comment by webcolor-in** [comment]
I can switch to new `?publink` but issue will be with twitter because getting link like `https://twitter.com/TheRickWilson/status/1183367552640126976` isn't available with posts.

**Comment by rkzack** [comment]
It will work if you pass a `t.co` link too

**Comment by webcolor-in** [comment]
Can I consider this as an enhancement? Both twitter and facebook will change apart from other url's. Estimate: 3 hours, will be delivered today.

**Comment by rkzack** [comment]
Go ahead

**Comment by webcolor-in** [comment]
Changes done, it was quite easy to migrate to `publink`, changes pushed.

**Comment by rkzack** [comment]
Ok, this is working better, thanks!  One more small issue and that should be it---  if there are no ratings on a question and its displaying "Needs more ratings"--  then don't display the other labels, ie on the screenshot below, remove `null [0%]` and `[0 ratings]` -- should just display: `Needs more ratings.`

<img width="390" alt="2019-10-14_1710" src="https://user-images.githubusercontent.com/35204816/66783940-1ae9f480-eea7-11e9-869b-1ad82f026c00.png">

**Comment by webcolor-in** [comment]
@rkzack - Does this apply on quick ratings question as well?

**Comment by webcolor-in** [comment]
Changes done and pushed

**Comment by rkzack** [comment]
This is working good, thank you. Closing issue.
