### ISSUE TITLE
More improvements to Chrome extension

### ISSUE THREAD

**Issue by rkzack** [ournews/extensions#25]
Hi @webcolor-in a couple more items:

- [x]  Bug, when a publisher result is not found in the new extension, the Newstrition card is not showing the normal error message like the previous extension would, can you add back the error message from the below screenshot (into the new design)? 

<img width="372" alt="2019-10-14_2228" src="https://user-images.githubusercontent.com/35204816/66795313-40402800-eed2-11e9-99e4-c80915e5affa.png">

- [x]  We'd like to improve the user flow experience for new users when not logged in on Twitter and Facebook, it's a little confusing (see below screenshots).  Can you please - [ ] change this so that for Twitter and Facebook, it says:  "Welcome!  To use our extension with Twitter or Facebook, please login or create a free account."  --  and then - [ ] don't open the main extension behind the login popup (unless they click the Login/Register). Otherwise right now you're left with a blank spinning window which looks like its broken, see second screenshot below.

<img width="393" alt="Screen Shot 2019-10-14 at 10 32 07 PM" src="https://user-images.githubusercontent.com/35204816/66795497-cceae600-eed2-11e9-80d5-13ce7facaf2b.png">

<img width="386" alt="Screen Shot 2019-10-14 at 10 34 20 PM" src="https://user-images.githubusercontent.com/35204816/66795505-cfe5d680-eed2-11e9-8683-857556f54d4f.png">

**Comment by webcolor-in** [comment]
Second one will take me around 3 hours to fix and test. Is that okay?

**Comment by rkzack** [comment]
Ok

**Comment by rkzack** [comment]
Yes this is approved.

**Comment by webcolor-in** [comment]
@rkzack - done
