### ISSUE TITLE
Login issues with Twitter

### ISSUE THREAD

**Issue by rkzack** [ournews/extensions#28]
Hi @webcolor-in we are seeing some login issues with Twitter--  if you click the "Login/Register" button while on Twitter, it opens the Login/Register screen, but after typing in your credentials, it comes back with an error `Requests to the server have been blocked by an extension.`  This seems to work correctly with all other sites except for Twitter.

Attached are screenshots of the error message and the Javascript Console. 
Also, we made a few minor formatting tweaks, so please do a git pull before proceeding.

<img width="382" alt="Screen Shot 2019-10-17 at 9 19 45 AM" src="https://user-images.githubusercontent.com/35204816/67012904-354aea80-f0c0-11e9-9f3a-3a25945e7285.png">

<img width="644" alt="Screen Shot 2019-10-17 at 9 20 34 AM" src="https://user-images.githubusercontent.com/35204816/67012914-39770800-f0c0-11e9-8b56-baacb1bc7028.png">

**Comment by webcolor-in** [comment]
Verified issue

**Comment by rkzack** [comment]
If this particular issue will take more than 2 hours to solve, then as a workaround, for Twitter only, we would be ok with a workaround where the login/register URL is loaded in a new tab, instead of within the browser extension popup.

**Comment by webcolor-in** [comment]
Yes this will take some time, there is CORS issue coming up that I need to dive deep and figure out. Temporarily I will make it to open new tab to login.

**Comment by webcolor-in** [comment]
temporary fix is pushed

**Comment by rkzack** [comment]
For Twitter this isn't working yet (see other issue)-- Twitter only sees the login if you manually refresh the login.  Also, this was supposed to be only for Twitter, but it's doing this now for Facebook too.  Please make the temporary fix for Twitter only.

**Comment by webcolor-in** [comment]
Top welcome login/register - though I fixed this but there is one issue, I see there was a commit from your end which adds URL to login/register link in that hyperlink so its not respecting anything else and simply redirects.

**Comment by rkzack** [comment]
Ok please fix that too, obviously this all has to work correctly.  We have to have login links, if you want to do them a different way, please just make them work correctly.

**Comment by webcolor-in** [comment]
If you click that top login/registration link no matter which website we are on it will redirect us to on news site replacing current url which is breaking rest all stuffs like no iframe no getting back to same site/redirection etc. 

I am going to revert this change and incorporate it in JS code. Estimate: 4 hours

**Comment by rkzack** [comment]
4 hours to add a simple login link?   There's no way it should take that long.  I think you're over-thinking this again. Just make it so if you click those login links it goes to the login page. I can't see how this could possibly take more than 15 minutes.

**Comment by webcolor-in** [comment]
No problem, the simplest I could do is remove those links added in html code.. so reverted your code and pushed to remote. I was asking for 4 hours to make it work in right manner like adding registration link with whatever url you had added and open this in script mode, handle for twitter and rest sites in different way but that's okay.

**Comment by rkzack** [comment]
This is not acceptable. It is confusing for the user.  Why can't this just behave exactly as if they click the "Login/Register" button in the popup?  It should be very simple.

Please fix these bugs, test fully. We still don't have a working product.

**Comment by webcolor-in** [comment]
I didn't get, Login/Register is made made to open a popup which will:
- Either show on site login in new tab (twitter)
- Show login within IFrame

Anything wrong in this?

**Comment by rkzack** [comment]
Yes, it's wrong because it takes multiple steps when it should only take one step. If you click the Login or Register text in the top, it should behave exactly the same way as the popup does--- not open the popup, which takes two steps, instead of one.

**Comment by webcolor-in** [comment]
The correct way is twitter does not take user outside to login, this ticket is for that but till we find that solution we needed temporary fix for which external window gets opened up. Agree it will not be permanent but just till we find a fix because something has changed on twitter and we need find/fix.

**Comment by rkzack** [comment]
This has nothing to do with Twitter.

**Comment by rkzack** [comment]
I'm talking about this:

<img width="389" alt="2019-10-19_1603" src="https://user-images.githubusercontent.com/35204816/67150791-2748c580-f28a-11e9-8e7b-64ee13728061.png">

If you click those links, it should take you directly here:

<img width="383" alt="2019-10-19_1605" src="https://user-images.githubusercontent.com/35204816/67150806-3af42c00-f28a-11e9-858d-a3c66e43bee0.png">

However, it's currently taking you here, which is wrong:

<img width="387" alt="2019-10-19_1606" src="https://user-images.githubusercontent.com/35204816/67150814-552e0a00-f28a-11e9-8732-cecc14249068.png">

**Comment by webcolor-in** [comment]
Instead of all this workaround let me fix the original issue and open ability to login by staying in same page.

**Comment by rkzack** [comment]
I think you are confusing two issues. The Twitter issue is resolved ok. It’s the link in the top bar that you changed that now needs to be fixed.

**Comment by webcolor-in** [comment]
I think there is some confusion here, let me share my understanding.

PROBLEM 1 - The original problem was user were not able to login via extension in Twitter website and that needs to be fixed.

The workaround was to open another tab where customer can login and then twitter page extension can auto refresh. [This was just workaround till we have fix]

So what I am saying is lets fix the original problem or CORS issue. 

PROBLEM 2 - Take user directly to login iframe when we click on login/register than showing confirmation popup. 

As of today popup is shown before we get into login screen no matter what link we click. So this will be another change to by pass popup when someone comes directly from login/register link, I will add that.

Is that good?

**Comment by webcolor-in** [comment]
PROBLEM 2 - Is fixed

**Comment by rkzack** [comment]
This looks like it's working now, thanks. Closing issue.
