### ISSUE TITLE
More Twitter issues, card info not clearing

### ISSUE THREAD

**Issue by rkzack** [ournews/extensions#31]
If you open more than one link in Twitter without refreshing the screen, the information from the prior card is not clearing out, so duplicate/incorrect information shows up on the next open. See screenshot below--  this was after clicking on a link from NYtimes.com -- the prior link I clicked was from Progressive and it's showing both. It should have only showed NYTimes.com

<img width="391" alt="Screen Shot 2019-10-19 at 2 44 25 PM" src="https://user-images.githubusercontent.com/35204816/67149910-29f1ed80-f27f-11e9-9e44-a210af976a62.png">

**Comment by webcolor-in** [comment]
Have added pub to hide when logo is present

**Comment by rkzack** [comment]
This is now broken even worse than before. Now it's showing the "How to use our extension on Twitter" text even on non-Twitter sites. Please fix this and test more thoroughly.  

<img width="398" alt="Screen Shot 2019-10-19 at 3 19 35 PM" src="https://user-images.githubusercontent.com/35204816/67150318-f9608280-f283-11e9-81eb-db338b61e99f.png">

**Comment by webcolor-in** [comment]
Fixed

**Comment by rkzack** [comment]
Now it's not working for Twitter again. Try this:  

1)  Visit `https://www.bbc.com/news/uk-politics-50110601` and open the popup
2)  Visit twitter.com and open the popup from the menu icon

You'll see the below, which is wrong again:

<img width="1170" alt="Screen Shot 2019-10-19 at 3 51 13 PM" src="https://user-images.githubusercontent.com/35204816/67150653-4b0b0c00-f288-11e9-8a15-9efdac2cc91c.png">

**Comment by rkzack** [comment]
I think the issue with these recent bugs is that it's not properly clearing out the prior article data when a new article is opened. Maybe put something in place so that every time the popup opens, it simply resets or clears all the variables?

**Comment by rkzack** [comment]
Any update on this item?

**Comment by webcolor-in** [comment]
This will be long poll to add reset for every item. 

> I think the issue with these recent bugs is that it's not properly clearing out the prior article data when a new article is opened. Maybe put something in place so that every time the popup opens, it simply resets or clears all the variables?

Every time you move from a page to another there is reload of entire page and everything that extension has gets destroyed so it never preserves anything whenever there is page reload. But if you are on same page like twitter and click on icon of one tweet and then another it replaces values.

The screenshot you shared shows that only few values could be loaded, yes that large spinner should be hidden in that case but the post you clicked had no logo/org name, it had limited info.

**Comment by rkzack** [comment]
No-- in the example I showed, it shouldn't have displayed the "Nutrition Label" card at all-- it should only have showed the "How to use our extension on Twitter" error. This is still a bug--  if you open a link from another site, and then open Twitter and click the menu icon, it's not showing the "How to use our extension on Twitter" error, it's showing a blank/errored Nutrition Label. 

This needs to be fixed. My suggestion is that every time you open the popup window, whether on a new site or the same site, simply clear all the variable data either by setting to null or destroying the variables. Perhaps there is another way, but either way, it's a bug that needs to get fixed.

**Comment by rkzack** [comment]
I've tested this several times and it's always failing. Just open any link on a page. Then go to twitter, and click the icon in the menu bar. It's always showing an empty/errored Nutrition Label card and isn't showing the "How to use our extension on Twitter" error like it should.

Perhaps another way to fix it, is that no matter what data you're receiving, if someone clicks the menu bar icon on Twitter (and not the individual icons on individual tweets), it should always discard any data and show the "How to use our extension on Twitter" error.

**Comment by webcolor-in** [comment]
Every time you move from one page to another like bbc.com -> open extension -> change url to twitter.com now your entire page gets destroyed and if you observe our extension disappears so there is nothing that it retains. Now after moving to twitter.com you will have to click extension again then it will load and start fetching API details.

**Comment by webcolor-in** [comment]
If you are not seeing that is separate issue but this is how it works when you move from a page to another where there is full page reload.

**Comment by rkzack** [comment]
Ok, so again, this is the bug for you to fix:

1)  Open any link, and open the browser extension
2)  Then, open Twitter, and click on the Our icon in the menu bar

It needs to always open the "How to use our extension on Twitter" screen. It is not doing that. Instead, it's opening a broken/errored Nutrition Label card. This is wrong and very confusing for users. Please fix so that it always opens the "How to use our extension on Twitter" message if you try to open from the menu bar. This is what we requested originally and still isn't working.

**Comment by webcolor-in** [comment]
All I am saying in that step 1 is not required for twitter to behave differently.. even if you directly open twitter.com it doesn't show that message where as if you open mobile version of twitter it does. 

Long story short, I have fixed and code pushed.

**Comment by rkzack** [comment]
Ok great, yes my initial testing shows this appears to be fixed, thanks! I have to leave for 3-4 hours now and will do further testing and hopefully close these issues out tonight. Please update your invoice, if everything is working then I will submit the payment tonight too. Thank you.

**Comment by webcolor-in** [comment]
It shouldn't create issue as its made similar to facebook ie internally take it as exclusion view.

**Comment by rkzack** [comment]
This is working well, thank you. Closing issue.
