### ISSUE TITLE
New bug, some links are not working in new version, but do work in older versions

### ISSUE THREAD

**Issue by rkzack** [ournews/extensions#32]
@webcolor-in after the latest changes, now we've noticed that the browser extension no longer works at all with many links in Chrome, that do work in Firefox. For example:

`https://www.miamiherald.com/news/business/article236460283.html`

It always loads the "Error: invalid URL or server timeout" error in Chrome,  however, the API responses are correct, and again, this works properly in Firefox. Please investigate. Thanks!

**Comment by webcolor-in** [comment]
Checking

**Comment by webcolor-in** [comment]
Its happening due to timeouts.. chrome is set for 10 sec where as ff is 30 sec.

**Comment by webcolor-in** [comment]
https://our.news/api/?publink=https://www.miamiherald.com/news/business/article236460283.html&_=1571590014566

is taking 10+ seconds

**Comment by rkzack** [comment]
Ok, I will look into that on the backend, in the meantime please set Chrome timeout to 30 seconds

**Comment by webcolor-in** [comment]
done

**Comment by rkzack** [comment]
Ok, this is working better, thanks. Closing issue.
