### ISSUE TITLE
Minor design issue

### ISSUE THREAD

**Issue by rkzack** [ournews/extensions#33]
@webcolor-in could you please make a small design change, as shown in these screenshots, please make the purple background fill the entire width and height within the drawn purple outline, on all the screens where it says "URL not yet indexed.". Thank you.

![2019-10-20_1903](https://user-images.githubusercontent.com/35204816/67167932-bf1ee000-f36c-11e9-938f-c5c266a2fd34.png)

![2019-10-20_1904](https://user-images.githubusercontent.com/35204816/67167931-bf1ee000-f36c-11e9-8fcd-ab87e7e32f42.png)

**Comment by webcolor-in** [comment]
Done

**Comment by rkzack** [comment]
Thank you, but to maintain design consistency, could you please make the height of the purple bar to be the same height as the blue bar on the Newstrition card (where it says Publisher Profile)?

**Comment by webcolor-in** [comment]
Done!

**Comment by rkzack** [comment]
Looks good, thanks. Closing issue.
