### ISSUE TITLE
Bug, encodeURI seems to not be working

### ISSUE THREAD

**Issue by rkzack** [ournews/extensions#37]
Hi @webcolor-in we're having a problem with some links, and the web server logs are showing that sometimes the extension isn't urlencode'ing its calls. For example you can see the below log entry, the URL is not encoded which is causing it to not match properly.

`67.242.87.170 - - [20/Oct/2019:20:09:05 -0400] "GET /api/?me=https://www.facebook.com/TwoButtonsDeep/photos/a.1703162189950736/2402901243310157/?type=3&__xts__%5B0%5D=68.ARDlP7Fhx6tkCfaPzreX9-kH_LQV_LUWDYnxzjhSVgJcqUf1G5gbt3BLdMH2aPCKnIqXvVCCQBAU-5NjF3rJGnPcYlg7_iKcsJbSpivuDKxLb7AEf4x7Kf2KhGXzxhK3ZZKwGzhlyEg2J_1eL7llBQ6zKSQQp1zXyzBqpSUEh6MvKRx4L871_pzybyc9CT7b7TeJH1wcRhANdnTq11KuB8V1v75xiGuWpLKi9wOltCcXIu9e4U62LAwdFzGz1FFWRZFRJIOGjw_81qNfGX__R_e7FFJIHLMhAwYvDna6Ru_gk0mvqecqZUPSPSuB7OETMpDPcGeMJjwu7YsiCPtlojCdsAWtaZtS40BsnjHuyUtc0ZZxjR3eixOjwJA&__tn__=-R&_=1571610656549 HTTP/1.0" 200 925 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36"
`

**Comment by webcolor-in** [comment]
If any url starts with `https://l.facebook.com/l.php?u=` it replaces `u` param with `decodeURIComponent` and send to backend API otherwise it send whatever url it gets as is

**Comment by webcolor-in** [comment]
In short there is no `encodeURI` anywhere, I just send url as it is and convert only when url is a parameter in facebook url.

**Comment by rkzack** [comment]
Ok, we do need all urls to be urlencoded, otherwise this will cause lots of problems. The logic should be very simple, just encode every url, as it is, before adding to the API GET calls, ie. the calls should look like:  https://our.news/api/?meta=encodedurlhere

**Comment by webcolor-in** [comment]
Have made that change, code pushed!

**Comment by rkzack** [comment]
Ok thank you. This was not working for us, but a little research showed that using the `encodeURIComponent` function might work better than just `encodeURI`, so we changed that, and now it's all working perfectly. This issue is now resolved.
