### ISSUE TITLE
Questions changing on refresh when sent in random order

### ISSUE THREAD

**Issue by rkzack** [ournews/extensions#40]
Hi @webcolor-in we adjusted the API to randomize the order of questions in the Q&A section at the top of the extension. However, when this is enabled, the questions are changing again with every refresh (presumably because the order is different now each time). See screencast:

https://www.screencast.com/t/vCH7brl1a

Could you please make it so that once loaded for any particular article, the questions either retain the initial order, or just don't refresh at all (unless the popup is closed and re-opened)?

**Comment by rkzack** [comment]
FYI-- we reverted the randomization for now so you won't see it if you try it.

**Comment by webcolor-in** [comment]
There is always question cache maintained and it checks if they are same then it does not refresh else it does. There is also additional check if article url has changed then it will refresh else it will not. 

So now I removed question cache check and it should do only article url check. So when article url changes it will reload all questions.
