### ISSUE TITLE
Publishing will be delayed

### ISSUE THREAD

**Issue by rkzack** [ournews/extensions#42]
Hi @webcolor-in when we went to publish the latest version, an error popped up:

<img width="501" alt="Screen Shot 2019-10-30 at 10 48 26 AM" src="https://user-images.githubusercontent.com/35204816/67868929-080c2c80-fb03-11e9-9750-8de843a7e5e8.png">

<img width="502" alt="Screen Shot 2019-10-30 at 10 49 20 AM" src="https://user-images.githubusercontent.com/35204816/67868935-0a6e8680-fb03-11e9-93ff-ccfcda58d073.png">

I tried adding the activeTab permission to the manifest, and it still seems to work ok. Do you have any idea if this will break something in the extension somewhere, or if its safe to add `activeTab`?

**Comment by rkzack** [comment]
@webcolor-in any thoughts on this issue?

**Comment by webcolor-in** [comment]
Here is what will happen - So if user opens our extension in a tab and navigates to other tab we loose permission to access the inactive tab to do anything. I think this is new security check from Google to avoid mining related problems.

**Comment by rkzack** [comment]
Ok, yea that makes sense, thanks. I don't think this will be a problem.
