### ISSUE TITLE
Can the extension place a popup iframe on a page even if its not manually opened?

### ISSUE THREAD

**Issue by rkzack** [ournews/extensions#43]
Hi @webcolor-in is it possible for the extension to popup an iframe on various pages even if the icon is not manually clicked by the user?

For example, user installs our extension, then navigates to a particular page, but doesn't open manually click the icon. Can we pop something up on their screen anyway?

**Comment by webcolor-in** [comment]
Yes we have full control and can do that. In your case it would be better to keep config with URLs where it can auto populate.

**Comment by rkzack** [comment]
Ok, great. So here's how we'd want this to work---  if they open a URL that's in our database, but they haven't yet clicked the icon--- we want it to wait 45 seconds, and then popup the QA questions sequence in the middle of their screen. 

The wait time (ie. 45 seconds) should be a configurable value that we'll include in the `extconfig` API call, so we can change the timer on the backend without updating the extension.

The QA data would be the same data as is already provided in via the API for any URL.

Two differences are (1) allow this to work for even users who are not logged in, but if not logged in, then at the end of the sequence, popup a new window encouraging them to signup or login; and (2) whether logged in or not, when any question pops up, send back a POST to our API to record that a popup has happened. 

An example of how we want this to work is on our site at this link:
`https://our.news/2018/09/14/ex-disneyland-princess-convicted-of-being-accessory-in-double-slaying/?ratingsPopup`

Could you provide an estimate for all this?

**Comment by webcolor-in** [comment]
Question - Login window will be opening our.news login page in another tab or some other way?

**Comment by rkzack** [comment]
For this another tab would be fine.

**Comment by webcolor-in** [comment]
And obviously we should hide it when extension popup opens up? Several sites has ads or other popups that they show in page after some time so this should override and show on top of all those if I am not wrong?

**Comment by webcolor-in** [comment]
Approx 22-25 hours

**Comment by rkzack** [comment]
Thank you @webcolor-in this is great information, we're considering how to proceed here.

One other alternative, what would be a time estimate, to just pop-open the current nutrition label exactly as it is now, but only if a user navigates to an articles that is already in the database?  Thanks!

**Comment by webcolor-in** [comment]
That will be quite less compared to above, roughly 5-6 hours at max.
