### ISSUE TITLE
Hide certain features for not-logged-in users, make Login message more prominent

### ISSUE THREAD

**Issue by rkzack** [ournews/extensions#44]
Hi @webcolor-in could you please update the extension quickly as follows:

1)  Change the text in the top header from "Please Login or Register to access all features." to "SIGN UP / LOGIN NOW TO UNLOCK ALL FEATURES" 

2) Make that text centered and extend the full width of the top purple header bar and be bright bold white, ensure the links work when clicked to take you to the login screen

3) Hide the following results on the Nutrition Facts card for not-logged-in users by replacing the results with a "Login" link which would open the login/register page:

a) All results under the Fact-Checks, so instead of displaying for example `False [100%]` display `Login` 

b) Same for the results for Spin, Trust, and Accuracy

This is an urgent task. Thank you!

Richard

**Comment by webcolor-in** [comment]
Question,

Newstrition Facts has Fact-Checks
Fact-Check card also has same 

So should we update both?

**Comment by rkzack** [comment]
Yes thank you.

**Comment by webcolor-in** [comment]
This will take around 5-6 hours

**Comment by rkzack** [comment]
Ok thanks please proceed.

**Comment by webcolor-in** [comment]
![Annotation 2019-11-20 080601](https://user-images.githubusercontent.com/55145799/69204329-a45aa980-0b6c-11ea-9fdd-d7780effc375.png)
That is the available space I will be using.

**Comment by rkzack** [comment]
Yes

**Comment by webcolor-in** [comment]
API calls are giving "502 Bad Gateway"

**Comment by rkzack** [comment]
Looks like there was an outage last night, please try again now.

**Comment by webcolor-in** [comment]
Changes pushed to ` satya-nov-19` branch

**Comment by rkzack** [comment]
Thanks. One thing--Right now both the "SIGN UP" and the "LOGIN" links are going to the login page, which may be a bit confusing for users who are trying to SIGN UP. 

Could you please make it so that if they click the "SIGN UP" link it takes them directly to the registration page here:  `https://our.news/register/?extension=1&ffi=0`

**Comment by webcolor-in** [comment]
I will trigger new window in that case and keep current one as it is

**Comment by webcolor-in** [comment]
code pushed

**Comment by rkzack** [comment]
Is there any reason this has to trigger in a new window?  We would prefer it it just stay in the extension like the login page does.

**Comment by webcolor-in** [comment]
Yes it's a registration form which has multiple options and we shouldn't
make users browse ournews pages within frame so keeping it separate.

**Comment by rkzack** [comment]
However, as it's currently worked before today, if someone goes to the Login page and then clicks Register, then the registration page stays within the extension and works perfectly. 

Can you please change this so that it opens the registration page within the extension frame?

**Comment by rkzack** [comment]
Also, can you please hide the Result scores on the "Ratings" card when not logged in as well, for Spin, Trust, and Accuracy questions?   Ie, should show:  `Results:  Login`

**Comment by webcolor-in** [comment]
That is not the only reason, there is 3 dots menu which also has registration link which opens in another tab. In order to maintain consistency with that I kept it same. If you want to change registration to be within extension then its 3-4 hours of change because we never incorporated this before so there is no code reuse.

**Comment by webcolor-in** [comment]
> Also, can you please hide the Result scores on the "Ratings" card when not logged in as well, for Spin, Trust, and Accuracy questions? Ie, should show: `Results: Login`

In that case we should hide in top QA as well? we show results there too. This will be separate scoping.

**Comment by rkzack** [comment]
Yes, please proceed.

**Comment by rkzack** [comment]
Please proceed with both the registration within extension and hiding in top QA. Thanks!

**Comment by webcolor-in** [comment]
Both are done and code pushed

**Comment by webcolor-in** [comment]
> That is not the only reason, there is 3 dots menu which also has registration link which opens in another tab. In order to maintain consistency with that I kept it same. If you want to change registration to be within extension then its 3-4 hours of change because we never incorporated this before so there is no code reuse.

I was able to reuse code here so it was quick

**Comment by rkzack** [comment]
This is working thanks. Closing issue.
