### ISSUE TITLE
Still getting warning about in-depth app reviews required

### ISSUE THREAD

**Issue by rkzack** [ournews/extensions#46]
Hi @webcolor-in we're still getting this error when attempting to publish the Chrome extension, re Publishing will be delayed, even after adding the `"activeTab"` permission to the manifest:

<img width="498" alt="Screen Shot 2019-11-20 at 2 28 18 PM" src="https://user-images.githubusercontent.com/35204816/69275087-b444ae80-0ba9-11ea-9e3d-b576c6fcff37.png">

This causes problems because it means we have to wait 3-5 business days for our extension to publish after every update. Could you please look into this and see why this is being caused and what we can do about it?  I even removed the `"<all_urls>"` item from the permissions array completely and Google still wants the in-depth review....  is it something else?

Thanks!  Richard

**Comment by webcolor-in** [comment]
I removed all site permission from `permissions` in manifest, hope that helps.

**Comment by rkzack** [comment]
Hmm, I'm not seeing any `permissions` changes in the manifest in your latest commits -- can you please check and make sure this commit happened and tell me what was changed?

**Comment by webcolor-in** [comment]
https://github.com/ournews/extensions/commit/40cc3e67c15eb8093abefbea9934bf08c31cac32

**Comment by rkzack** [comment]
Ok, yea we already tried removing that, and are still encountering the issue.  Any other ideas of permissions that we can remove?

**Comment by webcolor-in** [comment]
![Annotation 2019-11-25 193424](https://user-images.githubusercontent.com/55145799/69547030-d92a8e80-0fba-11ea-86a3-f655569b9795.png)
I found this in Google discussion forum. So it looks like they check for content script injection and we want our extension to work in several sites so we do need all site access. I don't know much on this one to prevent delay but will figure it out if there is any way to escape.

**Comment by webcolor-in** [comment]
Added all url permission back to manifest

**Comment by rkzack** [comment]
@webcolor-in Google is now requiring us to justify each permission in the manifest, per the below screenshot. Can you please provide better explanations than what I typed here?  Also, the same error about in-depth app reviews required is still happening.

Could this be because we have <all_urls> in both the content_scripts and permissions section?  Is it possible for those to be removed or somehow readjusted so we don't need those permissions?  Otherwise it can take weeks for them to approve even a simple update. Thank you.

<img width="925" alt="Screen Shot 2020-01-14 at 1 35 32 PM" src="https://user-images.githubusercontent.com/35204816/72371742-ff270200-36d2-11ea-9235-c4a068a9176e.png">

**Comment by webcolor-in** [comment]
tabs/activeTab - We want to handle extension icon click and show popup within active tab
webRequest - We want to by pass CSP and other network headers that block from rendering our.news as IFrame in any other site

Rest looks okay to me, we cannot do much here as we want to show in several URLs.

**Comment by rkzack** [comment]
While this issue happens every time we submit a new extension, it hasn't caused a problem-- the app has never been denied and it's never taken more than a few days to get approval. Closing issue for now.
