### ISSUE TITLE
Can the extension open a tab to a specific URL immediately upon installation?

### ISSUE THREAD

**Issue by rkzack** [ournews/extensions#48]
Hi @webcolor-in would it be possible for the extension to open a tab (ie. a user registration page) immediately upon the installation of the browser extension? If so, what's the time estimate? Thx!

**Comment by webcolor-in** [comment]
Yes it can be detected and registration page can be opened. My estimate is 2-3 hours.

**Comment by webcolor-in** [comment]
We can also detect updates and open new tab.

**Comment by rkzack** [comment]
Ok great, thanks. Please proceed to detect initial installation only, and in that instance, direct people to these links:

Chrome -  `https://our.news/register/?extension=2&ffi=0&CID=ON.Chrome`
Firefox -  `https://our.news/register/?extension=2&ffi=0&CID=ON.Firefox`

**Comment by webcolor-in** [comment]
Done, code pushed

**Comment by rkzack** [comment]
This is working, thank you. Closing issue.
