### ISSUE TITLE
Adblockers interfere with the extensions

### ISSUE THREAD

**Issue by rkzack** [ournews/extensions#5]
Most popular Adblocker extensions seem to block our extensions from working. When enabled, our extensions will open, but the spinner spins forever and no data will display on screen.

We're testing using the Chrome version, and this adblocker:  getadblock.com

**Comment by rkzack** [comment]
I've created a new branch called chrome_no_adblock_warning -- this branch disables the Adblock detection error message -- so that this can be tested. To test this, after grabbing the chrome_no_adblock_warning branch, you can load the extension unpacked and test.

**Comment by rkzack** [comment]
Here's a screencast video demonstrating the problem:
https://www.screencast.com/t/h62AJzBy

**Comment by Happyandhappy** [comment]
When enabled AdsBlocker, chrome.extension.sendRequest is not working, but when disabled , it's working,
not sure about the reason,
I estimate 7 hrs for this
Thank you

**Comment by rkzack** [comment]
Ok, thank you. Up to 7 hours is approved. Please proceed.

**Comment by Happyandhappy** [comment]
Thank you

**Comment by rkzack** [comment]
Please pause/hold work on this for now. We found a typo that may have resolved the issue.

**Comment by Happyandhappy** [comment]
Ok, got it
