### ISSUE TITLE
Bug, Login link in Q&A section doesn't update after logging in

### ISSUE THREAD

**Issue by rkzack** [ournews/extensions#51]
Hi @webcolor-in we've discovered a bug in the latest changes, the Login link in the Results: section of the top Q&A doesn't update to the results after a users logs in.  To reproduce this error, load the extension when not logged in. You will see that it does properly replace the `Results: Login` line. However, after logging in, when the extension refreshes, it should then be showing the correct results. However, it still shows the 'Results: Login' line. See screenshot:

<img width="309" alt="Screen Shot 2019-11-29 at 2 16 05 PM" src="https://user-images.githubusercontent.com/35204816/69887326-62d8a580-12b4-11ea-846e-3ddbdc0020f0.png">

Could you please fix? Thanks!

**Comment by webcolor-in** [comment]
Fixed

**Comment by rkzack** [comment]
This is working well thanks. Closing issue.
