### ISSUE TITLE
Tracking in Q&A section

### ISSUE THREAD

**Issue by rkzack** [ournews/extensions#52]
Hi @webcolor-in we need to add tracking to the Q&A section at the top of the extension, so that we can monitor how often the questions are answered-- this will help us determine the CTR for each question. Could you please configure the tracking as follows:

1) The tracking is a little different for the FIRST question in the sequence, -vs- all remaining questions. For the FIRST question only, here's how it should track:

a) If a user clicks Skip, then POST these values:

`popups=slug`  -- where slug = the `slug` value of the question
`popupsval=2`  -- 2 indicates to the API a Skip action
`nid=nid` -- where nid = the `nid` of the underling article, from `results.meta.nid`

b) If a user answers the question, then POST these values, in addition to the answer post:

`popups=slug`  -- where slug = the `slug` value of the question
`popupsval=choiceid`  -- where `choiceid` = the ID of the choice they picked 
`nid=nid` -- where nid = the `nid` of the underling article, from `results.meta.nid`

2) For all other questions in the sequence after the first question:

a) Immediately when a question opens, POST these values:

`popups=slug`  -- where slug = the `slug` value of the question
`popupsval=0`  -- 0 indicates to the API a question has been displayed
`nid=nid` -- where nid = the `nid` of the underling article, from `results.meta.nid`

This will return a value for `popid` which will be used in the next steps.

b) If the user then clicks Skip, then POST these values:

`popups=slug`  -- where slug = the `slug` value of the question
`popupsval=2`  -- 0 indicates to the API a question has been displayed
`nid=nid` -- where nid = the `nid` of the underling article, from `results.meta.nid`
`popid=popid` -- where popid = the `popid` from step (a) above

c) If the user answers the question, then POST these values, in addition to the answer post:

`popups=slug`  -- where slug = the `slug` value of the question
`popupsval=choiceid`  -- where choiceid =  the ID of the choice they picked 
`nid=nid` -- where nid = the `nid` of the underling article, from `results.meta.nid`
`popid=popid` -- where popid = the `popid` from step (a) above

**Comment by webcolor-in** [comment]
Bit tricky one but can do it, my estimate is around 4-5 hours.

**Comment by rkzack** [comment]
Ok, please proceed asap.

**Comment by webcolor-in** [comment]
Pushed to `satya-dec-19` branch

**Comment by rkzack** [comment]
This is working well, thanks. Closing issue.
