### ISSUE TITLE
Extension improvements

### ISSUE THREAD

**Issue by rkzack** [ournews/extensions#55]
Hi @webcolor-in I hope you are well. We'd like a few small changes to the extensions please-- make sure to grab the latest master branch and start a new branch for these issues.

- [ ]  Summary Card -- Author Section -- always right-align the "Unverified" or "Verified" label for Newstrition Status. Sometimes it aligns left as shown below.

<img width="394" alt="Screen Shot 2019-12-10 at 4 14 29 PM" src="https://user-images.githubusercontent.com/35204816/70569578-33555300-1b68-11ea-9ac7-16d92179a166.png">

- [x] Summary Card -- Author Section -- change the "Unverified" or "Verified" label to be a link that points to the Author's page, which is constructed based on the `aid` value as follows, ie, for aid 38674, the authors page URL is `https://our.news/a/?aid=38674`

- [x] Top Q&A Section --  when logged in, instead of showing the actual results of each question, we want to hide the results unless the use clicks a link.  For example on the below, instead of showing "Results: Approve [70%] [10 Ratings]"  it should show "Results:  Click to view."  and after clicking the "Click to View" link, it should show "Results: Approve [70%] [10 Ratings]"

<img width="392" alt="Screen Shot 2019-12-10 at 4 14 20 PM" src="https://user-images.githubusercontent.com/35204816/70569564-2f293580-1b68-11ea-98c3-a0ade1a5317b.png">

Note, these screenshots were taken with Firefox version on this link:  `https://www.cnn.com/2019/12/10/politics/usmca-nancy-pelosi-donald-trump-trade-deal/index.html`

**Comment by rkzack** [comment]
- [ ] Top Q&A Section -- Also, when users click the "Click to View" link for the results, it should send a tracking POST to the API `viewresult` with a value of the `qid` of the `question`.

**Comment by webcolor-in** [comment]
Estimate - 5 hours

**Comment by rkzack** [comment]
Ok please proceed thanks.

**Comment by webcolor-in** [comment]
All changes are done and pushed to - `satya-dec-12-19`

**Comment by webcolor-in** [comment]
I am using `nid` and not `qid` same as others

**Comment by rkzack** [comment]
Thanks but in this case we need `qid` value passed to `viewqid` variable please.

**Comment by webcolor-in** [comment]
What is `qid` then? How do I get that value?

**Comment by rkzack** [comment]
`qid` is the id of the question that the user is requesting the result for.  Its in the API results.

**Comment by webcolor-in** [comment]
![Annotation 2019-12-12 193818](https://user-images.githubusercontent.com/55145799/70718836-fd0a0600-1d16-11ea-9be5-0c46831cf683.png)
Here is the response that I see, there is no `qid` in this

**Comment by rkzack** [comment]
Ah, apologies, the value of `viewqid` should be the `slug` value like 'MISINFORMATION_DEEPFAKE' etc

**Comment by webcolor-in** [comment]
Done

**Comment by rkzack** [comment]
Thanks. One issue so far, in Firefox, this is not working right yet:  "Summary Card -- Author Section -- always right-align the "Unverified" or "Verified" label for Newstrition Status. Sometimes it aligns left as shown below."  -- this needs to be right-aligned but it doesn't always do that. Thanks

**Comment by webcolor-in** [comment]
I was able to reproduce this, fixed now.

**Comment by rkzack** [comment]
Looks good, thanks!  Closing issue.
