### ISSUE TITLE
Next round of extension improvements

### ISSUE THREAD

**Issue by rkzack** [ournews/extensions#57]
Hi @webcolor-in happy holidays!  Here's the next round of extension improvements for you to look at and create an estimate for. We'd like to proceed quickly if possible.

- [x] On these two links, the spinner and the triple-dots icons are distorted, please fix:

`https://www.cnn.com/2019/12/30/us/texas-church-shooting-monday/index.html `
`https://www.timesunion.com/news/article/She-gave-her-best-and-expected-the-same-in-14939276.php `

<img width="387" alt="Screen Shot 2019-12-30 at 4 55 19 PM" src="https://user-images.githubusercontent.com/35204816/71605717-29a48700-2b39-11ea-97e6-46c0ab68e69a.png">

- [x] Add a way for users to hide the Q&A box— in the bottom right corner of the Q&A box, add a small up-arrow icon (&#9650;) that when clicked, hides the entire Q&A section, but leaves behind a down-arrow icon (&#9660;) that when clicked, shows the entire Q&A section. Use a cookie to remember user preference on this— if they’ve previously hidden Q&A then it should hide by default (unless they’ve later un-hidden it, toggle this).

- [x] Changes to Summary card—

    - Change “Fact-Checks” to “Fact Checks”
    - Add a new section called “Sources” under the Fact Checks section, displaying the Article Sources as shown in below mockup. 
    - Only show up to three Sources and two User Contributed sources
    - Put a thin horizontal line between Sources and Sources - User Contributed, and also between the Fact Checks and Sources section

<img width="391" alt="summary-card-sources" src="https://user-images.githubusercontent.com/35204816/71605764-830cb600-2b39-11ea-88fb-31dceff187a0.png">

- [x] Changes to Fact-Check card—

    - Change the tab name from “Fact-Check” to “Fact Check”
    - Remove the top purple header entirely 

- [x] Changes to Ratings card —

    - Remove the “RATE THIS ARTICLE” header entirely
    - Under Relevance, change what it says if there aren’t enough results from “#Not Rated []”  to “Not yet rated.”

- [x] Changes to Newstrition card — 

    - Remove the blue "Newstrition Label" header entirely. Instead, on this card, change the bottom footer to blue, and put the FFI logo in the bottom left corner

    - Move the "Claim this profile" link to the top as shown in the mockup as "Claim Profile".
    - Add logic to the `description` field so that it will only show a maximum of five lines, including space for a new "more -->" link that should link to the publishers profile... if necessary, clip the spaces needed to do this using css
    - Move the horizontal line under the description to beneath the publishers AllSides rating
    - Remove the “Owned By: “ text/line
    - Move the "Est. Date" field below the Location field
    - Move the AllSides image to be right-aligned as shown in mockup
    - Add an author section as shown in the below mockup 
    - If the author doesn't have an image, use this image as a default:

![newstrition-card-authors](https://user-images.githubusercontent.com/35204816/71605701-0bd72200-2b39-11ea-91b1-8c1e24ec1397.png)

**Comment by webcolor-in** [comment]
I ack to have read this, I will share estimates by tomorrow and take your approval before working on it.

**Comment by webcolor-in** [comment]
`If the author doesn't have an image, use this image as a default`

Please attach this image

**Comment by webcolor-in** [comment]
My rough estimate is 8 hours for all changes.

**Comment by rkzack** [comment]
![default_profile](https://user-images.githubusercontent.com/35204816/71681248-2a683380-2d5a-11ea-8d24-691f21822ce6.png)

**Comment by rkzack** [comment]
Ok great, thank you. Please proceed.

**Comment by rkzack** [comment]
Hi @webcolor-in just checking in, wondering if you've gotten started on this or have any questions?

**Comment by webcolor-in** [comment]
Due to some personal emergency I am traveling this entire week so I can do this on Sunday. Let me know if any changes in project plan.

**Comment by rkzack** [comment]
Ok, I am sorry to hear of the personal emergency.  This is an urgent project, please let us know if you won't be able to complete it in Sunday as we must have it done by next week.

**Comment by webcolor-in** [comment]
Thanks for understanding Richard, Yes it will be done by Sunday.

**Comment by webcolor-in** [comment]
I see one concern ie height of popup with QA being open, what shall we do? use scrollbars?

**Comment by rkzack** [comment]
Yes, if possible I think the popup should expand to fill 100% of the current browser window, and if its bigger than that, then add visible scrollbars on the right side.  Thank you.

**Comment by webcolor-in** [comment]
![Annotation 2020-01-12 161604](https://user-images.githubusercontent.com/55145799/72217650-e265bf80-3556-11ea-8698-d76633b1cb97.png)

Question - As all cards share same footer so this will be the new footer shown in all 4 tabs?

**Comment by webcolor-in** [comment]
Question - What are the fields for author section? Is that `claim profile` and `allside media` repeatation in author section?

**Comment by webcolor-in** [comment]
`Add logic to the description field so that it will only show a maximum of five lines, including space for a new "more -->" link that should link to the publishers profile... if necessary, clip the spaces needed to do this using css`

There is way to clip in CSS but that won't add more link so I have limited to 36 words based on rough estimate of number of words in a line.

**Comment by rkzack** [comment]
Hi @webcolor-in, to answer your questions:

1). Question - As all cards share same footer so this will be the new footer shown in all 4 tabs?  -- Answer- No, this new footer must only show on the Newstrition card.

2) Question- What are the fields for author section?
Answer-  Look in the `meta.authors` array within the `exturlpublicnid` or `exturlprivatenid` arrays

3) Is that claim profile and allside media repeatation in author section?
Answer-   No, this data is unique to the author, not a repeat from the publisher. Claim Profile should be a link to the author profile - our.news/a/?aid=<insert aid here> -- and the allsides data is in the `meta.authors` array

**Comment by webcolor-in** [comment]
![Annotation 2020-01-12 205348](https://user-images.githubusercontent.com/55145799/72221144-a98d1100-357d-11ea-9fe2-e10eadb1ee17.png)

What to be done for this? Should this text also move along with Claim Profile? If so then we will have very less space to fit this.

**Comment by rkzack** [comment]
As you can see in the mockup design posted above, the words "Profile Unclaimed." have been removed and should no longer appear.

**Comment by webcolor-in** [comment]
I was not involved in "Claim Profile" changes before so have less idea, there is also "Login to Claim" which will be shown when user is not loggedin, I am moving this one too.

**Comment by rkzack** [comment]
Please make it look exactly like in the mockup in this very issue above (the screenshot in the issue description above). No "Profile Unclaimed." or "Long to Claim" text is needed just "Claim Profile".

**Comment by webcolor-in** [comment]
![Annotation 2020-01-13 093739](https://user-images.githubusercontent.com/55145799/72232636-5ef4ae80-35e8-11ea-9b35-da1ca1969e44.png)

Should I use `newstrition.verifiedhelp` itself here?

**Comment by webcolor-in** [comment]
The newstrition allside feature is not implemented in Firefox so you need it now or I should skip this in Firefox version? If you need this my revised estimate will be 12 hours in total, let me know.

**Comment by rkzack** [comment]
Your question:  Should I use newstrition.verifiedhelp itself here?  
Answer:  Yes

And Yes-- please proceed with AllSides feature in Firefox.  Thanks!

**Comment by webcolor-in** [comment]
Changes done, code pushed to branch - https://github.com/ournews/extensions/tree/satya-jan-12

**Comment by rkzack** [comment]
Ok thank you, I will begin testing now.

**Comment by rkzack** [comment]
Hi @webcolor-in nice work on this!   A few issues, and changes please:

1)  On the Summary card, don't display the entire "Sources - User Contributed" section if there are no user contributed sources. 

2)  When using this link:  `http://actionnews3.com/rat-meat-has-been-sold-as-chicken-wings/`  -- we notice two issues.  First, the "Claim Profile" link looks like it is just floating -- so in case there are no social icons the Claim Profile link should align to the right of the box.  Second, the author image on this page is shrunk very small, that image should always be the same size.

<img width="397" alt="Screen Shot 2020-01-13 at 8 31 49 AM" src="https://user-images.githubusercontent.com/35204816/72260478-f6560380-35e0-11ea-8278-a3d2e795f5ba.png">

3) Related to point 2 above, sometimes we see the "Claim Profile" link in all uppercase and/or word-wrapped, such as on this link:  `https://worldnewsdailyreport.com/california-pro-choice-activist-proudly-breaks-world-record-by-getting-her-27th-abortion/`   -- Please make sure it isn't converted to all-uppercase and that it doesn't word wrap ever.

4)  On the Newstrition card, under the new Author section,  use `meta.authors.verifiedhelp` instead of `newstrition.verifiedhelp` for the (?) icon.  The `newstrition.verifiedhelp` data should still be used for the Publisher section (?) icon but not for Authors.

5) On the Ratings card, under the Relevance section, add two more ratings button choices:  "#False" and "#Junk" 

6) On the Ratings card, in the event a user profile image is a broken image (like below screenshot), then replace it with this image (I think you can do this automatically with CSS):  https://img.our.news/img/default-publisher.png

<img width="391" alt="Screen Shot 2020-01-13 at 8 44 55 AM" src="https://user-images.githubusercontent.com/35204816/72260618-403ee980-35e1-11ea-88cc-7a1a1b4e74d4.png">

**Comment by webcolor-in** [comment]
1, 2 & 3 is fixed.. our.news site is down so I am waiting on that.

**Comment by rkzack** [comment]
Thanks, but the site is not down. What is your IP address?  Maybe caught in IPS I can whitelist.

**Comment by webcolor-in** [comment]
![Annotation 2020-01-14 084353](https://user-images.githubusercontent.com/55145799/72311242-0554b880-36aa-11ea-9402-0575d142a17a.png)
I see it shows this, I just found few URLs where things should work so not blocked on it now.

**Comment by rkzack** [comment]
Ok also the browser extensions access `data.our.news/api` now

**Comment by webcolor-in** [comment]
All done and code pushed

**Comment by rkzack** [comment]
2-  That looks better but now the (?) icon is a bit distorted on that page `http://actionnews3.com/rat-meat-has-been-sold-as-chicken-wings/` (see below).

6-  We're still seeing broken profile images

**Comment by webcolor-in** [comment]
For point 6 - can you please send any URL?

**Comment by rkzack** [comment]
6 - `https://worldnewsdailyreport.com/california-pro-choice-activist-proudly-breaks-world-record-by-getting-her-27th-abortion/`

**Comment by rkzack** [comment]
2- 
<img width="575" alt="Screen Shot 2020-01-14 at 9 40 07 AM" src="https://user-images.githubusercontent.com/35204816/72354667-24f0de80-36b4-11ea-949f-a23d78656ab4.png">

**Comment by webcolor-in** [comment]
It has URL just that URL is not appropriate - https://media.licdn.com/dms/image/C4D04AQFM097LNOMNoA/profile-originalphoto-shrink_450_600/0?e=1538611200&#038;v=beta&#038;t=dUPnzjYkmlBnoZhs9OoHQ8ca39XAwVjx5opw7YBizT8

**Comment by rkzack** [comment]
Yep, in case of broken images, use CSS to hide or replace the image.

**Comment by rkzack** [comment]
Here's a way I found using google, there are other ways:  https://bitsofco.de/styling-broken-images/

**Comment by webcolor-in** [comment]
They are using content attribute which works for text and text based icons like fontawesome, it won't work for our use case. Let me check alternate options.

**Comment by webcolor-in** [comment]
#6 is fixed, I added js script.

**Comment by webcolor-in** [comment]
Point 2 is also fixed

**Comment by rkzack** [comment]
Ok thanks, 2 and 6 look good.  Couple more minor things:

7-- We need to use less space in the Q&A widget, can you move the arrow up a line and remove the extra line break that's under the "Results: Click to view" line?

8-- It looks like the "Nutrition Facts" heading has been reduced to normal text now, please restore that to the heading font/style exactly what it looked like before. 

<img width="394" alt="Screen Shot 2020-01-14 at 11 44 06 AM" src="https://user-images.githubusercontent.com/35204816/72363696-3db4c080-36c3-11ea-8247-6715f26e5eb5.png">

"Nutrition Facts" should be always like:

<img width="389" alt="Screen Shot 2020-01-14 at 11 45 14 AM" src="https://user-images.githubusercontent.com/35204816/72363767-5d4be900-36c3-11ea-997e-e57686731d07.png">

**Comment by webcolor-in** [comment]
8 - done

**Comment by webcolor-in** [comment]
7 - I can reduce space but not remove that entire line because arrow itself is present on that line or we should go with better pattern.

**Comment by rkzack** [comment]
7- please find a way to reduce the space and still look visually appealing.

**Comment by webcolor-in** [comment]
Have reduced a bit

**Comment by rkzack** [comment]
Hmm, we pulled the latest code and reloaded, but neither 7 nor 8 are fixed for us.

**Comment by webcolor-in** [comment]
Here are commits - https://github.com/ournews/extensions/commits/satya-jan-12

**Comment by rkzack** [comment]
And your fixes are not working. Please make sure to test your own code and please fix.

**Comment by rkzack** [comment]
<img width="468" alt="Screen Shot 2020-01-14 at 12 22 54 PM" src="https://user-images.githubusercontent.com/35204816/72366697-c71ac180-36c8-11ea-94a9-8a9f78836f9f.png">

**Comment by webcolor-in** [comment]
My mistake I did not push that font fix commit, done just now

**Comment by webcolor-in** [comment]
But for spacing I see my changes are working, I have reduced spacing at the bottom of arrow to 5px from 15px. Plus when it collapses QA it has reduced spacing top/bottom of arrow than before.

**Comment by webcolor-in** [comment]
done

**Comment by rkzack** [comment]
This work was successfully completed. Closing issue.
