### ISSUE TITLE
More enhancements and bugs to address

### ISSUE THREAD

**Issue by rkzack** [ournews/extensions#62]
Hi @webcolor-in some new urgent items for the extension, can you address asap?

1)  Please add the "Caution" label code from the previous issue (#60) to the top of the Newstrition tab as well

2)  On the Newstrition tab, when an article is indexed, it is correctly changing the footer to the blue color and adding the Freedom Forum Logo.  However, this doesn't seem to be working when an article isn't yet indexed.  For example, here's a correct footer on an indexed article:

https://www.cnn.com/2020/04/20/us/protests-coronavirus-stay-at-home-orders/index.html

<img width="392" alt="Screen Shot 2020-04-20 at 10 46 13 AM" src="https://user-images.githubusercontent.com/35204816/79765108-33264a80-82f4-11ea-9582-0e46462f0dd0.png">

And here's an incorrect footer on a non-indexed article (it should be blue with the logo):

https://apnews.com/34b48ffba057099eaee794342bce448e

<img width="392" alt="Screen Shot 2020-04-20 at 10 47 34 AM" src="https://user-images.githubusercontent.com/35204816/79765256-5ea93500-82f4-11ea-9d6a-0fc8e72ed05a.png">

3) The extension is misbehaving on articles that aren't eligible to be indexed. For example, if you visit "https://cnn.com" and open the extension, it shows the below.  In this case, it should be displaying the error message "Oops, this URL is not eligible to be indexed." message within the white space at the top, and then also on the Summary, Fact Check, and Ratings cards too.  

For URLs that aren't eligible to be indexed, the `exturlprivate/exturlpublic` API response will have an error response in the JSON that says:  "Meta: Link not eligible for indexing"

<img width="390" alt="Screen Shot 2020-04-20 at 10 49 56 AM" src="https://user-images.githubusercontent.com/35204816/79765995-63bab400-82f5-11ea-8768-26adeb7f08a1.png">

**Comment by webcolor-in** [comment]
1 & 2 is done and code pushed to branch  satya-apr-21

**Comment by webcolor-in** [comment]
3 is done

**Comment by rkzack** [comment]
Confirmed that items 1 and 2 look good. Thanks!

Item 3 needs more work as we discussed in Slack.

**Comment by webcolor-in** [comment]
#3 - updated and code pushed

**Comment by rkzack** [comment]
All looks good, thanks!  Closing issue.
