### ISSUE TITLE
More issues with extensions

### ISSUE THREAD

**Issue by rkzack** [ournews/extensions#69]
Hi @webcolor-in in the extensions, in the Q&A section at the top, could you please change the link from "Login" where it opens the login screen, to be:

**Login** or **Join** to see Results.

Where the Login link would open the login screen as it does now, but the Join link would open a new browser window opening this URL:  https://our.news/join/?CID=ON.Chrome

<img width="411" alt="Screen Shot 2020-06-10 at 4 15 44 PM" src="https://user-images.githubusercontent.com/35204816/84314252-b8c8b880-ab35-11ea-8191-e18771f1cb3a.png">

**Comment by webcolor-in** [comment]
Changes done, code pushed

**Comment by rkzack** [comment]
Looks good, thank you!  Closing issue.
