### ISSUE TITLE
Improve Twitter functionality in certain cases

### ISSUE THREAD

**Issue by rkzack** [ournews/extensions#70]
Hi @webcolor-in it looks like the extensions aren't setup to use the correct links if someone has landed directly on a URL for a specific tweet. For example, if you visit:

https://twitter.com/OverdoseLive/status/1267517173674672128

Thats a landing page for that tweet. If you tap the Our.News icon either in the Chrome Bar or in the Tweet itself, it seems to be using the wrong URL for the `publink` and `exturlpublic` calls:

```
74.89.82.103 - - [10/Jun/2020:21:07:21 +0000] "GET /api/?publink=https%3A%2F%2Fhelp.twitter.com%2Fusing-twitter%2Fhow-to-tweet%23source-labels&_=1591822841082 HTTP/1.0" 200 1115 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36"
74.89.82.103 - - [10/Jun/2020:21:07:21 +0000] "GET /api/?exturlpublic=https%3A%2F%2Fhelp.twitter.com%2Fen%2Fusing-twitter%2Fhow-to-tweet%3Flang%3Dbrowser&_=1591822841081 HTTP/1.0" 200 2722 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36"
```

Could you please check and see if this can be fixed?  Thanks!

**Comment by webcolor-in** [comment]
I was debugging this and I see this post does not have any external link so its taking twitter help hyperlink.

**Comment by webcolor-in** [comment]
Have updated and code pushed to satya-jun-09 branch :)

**Comment by rkzack** [comment]
Hi, I tried this but it's still not working for me. 

In these cases -- when on a direct landing page or a tweet --  it needs to do more than just remove the Twitter help hyperlink, it needs to use the URL from the menu bar for all the API actions. You can determine if you're on a Tweet landing page if the URL in the menu bar contains both "twitter.com" and "/status/".

**Comment by webcolor-in** [comment]
You are absolutely right, I updated and checkedin.

**Comment by rkzack** [comment]
This works good, nice work thank you!  Closing issue.
