### ISSUE TITLE
Error about cookies in Chrome extension when logging in

### ISSUE THREAD

**Issue by rkzack** [ournews/extensions#74]
Hi @webcolor-in users are getting this error in the Chrome extension when trying to login:

```Error: Cookies are blocked or not supported by your browser. You must enable cookies to use WordPress.```

This doesn't appear to be happening with Firefox. And, this doesn't happen if you login directly via the website. It only happens within the browser login screen.  Can you please investigate?  Thank you.
<img width="389" alt="Screen Shot 2020-09-01 at 1 30 19 PM" src="https://user-images.githubusercontent.com/35204816/91886451-59bba100-ec57-11ea-9eab-e51c5aba06fe.png">

**Comment by webcolor-in** [comment]
Can you share URL where you observed this issue? I think this issue is limited to few sites and not appearing in all.

**Comment by rkzack** [comment]
https://gizmodo.com/trump-spreads-conspiracy-theory-so-stupid-im-struggling-1844916383?rev=1598987524392

**Comment by webcolor-in** [comment]
Most of the forums show that this requires some correction in wp-config.php file. 
https://www.parrotcreative.co.uk/cookies-blocked-or-not-supported-by-browser/#:~:text=To%20fix%20the%20%E2%80%9CCookies%20are,into%20your%20WordPress%20admin%20dashboard.
https://stackoverflow.com/questions/20941328/wordpress-admin-login-cookies-blocked-error-after-moving-servers

**Comment by rkzack** [comment]
Thanks, but there have been no changes to our wp-config.php file for months, and this is a new problem that has only appeared recently. It also only appears in Chrome when using the browser extension. 

Going thru the suggestions from your links, we've already checked or tried the following which haven't worked:

-- Cleared all cache/settings and reloaded Chrome
-- We have not added any caching plugins lately
-- We have not changed hosting providers or migrated the site
-- Tried the "permanent fix" one suggested, it didn't work

Is it possible that cookies have somehow been restricted by Chrome within browser extensions?
I think this is a Chrome issue, not a Wordpress issue...

**Comment by webcolor-in** [comment]
Chrome had made some recent changes in cookies policies so got to check if
this is happening because of that. I feel change will be in site but not
sure what that change should be for example there was cross site cookie
setting policy that Chrome modified recently which made several site to
change their cookie structure.

**Comment by rkzack** [comment]
Ok. Then for now, can you please disable the login from within the extension window, and instead if someone clicks Login, have it open the login screen in a new tab?  That seems to work manually, we need to fix this asap. Thank you.

**Comment by webcolor-in** [comment]
I made changes and pushed to `satya-2020-09-04` branch
