### ISSUE TITLE
Broken images appearing

### ISSUE THREAD

**Issue by rkzack** [ournews/extensions#75]
Hi @webcolor-in another browser extension issue has appeared, on certain articles it's showing a broken image in the preview. Can you change this so that in these cases, instead of showing a broken image, it shows no image at all?

Ex:  `https://gizmodo.com/trump-spreads-conspiracy-theory-so-stupid-im-struggling-1844916383?rev=1598987524392`

<img width="398" alt="Screen Shot 2020-09-01 at 3 39 07 PM" src="https://user-images.githubusercontent.com/35204816/91898347-94c6d000-ec69-11ea-86f1-a670dec8e892.png">

**Comment by rkzack** [comment]
One of our other developers implemented a solution that works on our website, can you take a look at this page:  `https://our.news/2020/09/01/trump-spreads-conspiracy-theory-so-stupid-im-struggling-to-write-a-headline-for-it/`  -- that has the exact same (broken) image but somehow it's hidden and appears as an empty white box.

We can't figure out why the WP backend is acting this way on broken images, ideally it should give a 404 error but we're not sure how to fix that. Unfortunately this issue comes up a lot so we need to find a way to hide on the extension.

**Comment by webcolor-in** [comment]
I checked the site and they are using image as background image. So it won't show broken image if it does not load the image. I will follow the same, the only drawback of this approach is we need to fix height/width of image. So if I create a box of 45x45px then a rectangle image will look squeezed. I am creating rectangular box 65x45px as most of the pictures are rectangular.

**Comment by webcolor-in** [comment]
done and code pushed

**Comment by rkzack** [comment]
I tested but something is wrong here-- instead of blanking out only the image, it looks like its blanking out the whole article preview including the title, etc. See attached screenshot.

<img width="765" alt="Screen Shot 2020-09-08 at 11 56 38 AM" src="https://user-images.githubusercontent.com/35204816/92499920-74979380-f1ca-11ea-92c7-94100f9e2e70.png">

**Comment by rkzack** [comment]
That's for Firefox, it seems to work properly in Chrome.

**Comment by webcolor-in** [comment]
May be some other issue as it's working fine for me. Let me check if I can reproduce your issue or you can test previous version to confirm.
![image](https://user-images.githubusercontent.com/55145799/92500622-09c27880-f21b-11ea-9c26-ed5c3ab8e1c5.png)

**Comment by rkzack** [comment]
Seems to only happen for me with Firefox, Chrome works ok...

**Comment by rkzack** [comment]
@webcolor-in any luck with this issue for Firefox?

**Comment by webcolor-in** [comment]
Q - Did you start seeing this issue after I made broken image fix or was it even before??

**Comment by rkzack** [comment]
I only noticed it after you made the broken image fix, I am not sure if it existed previously but am fairly certain it didn't.

**Comment by rkzack** [comment]
I can no longer duplicate this issue, not sure what the problem was, but its solved now. Closing.
