### ISSUE TITLE
Add warning label within DOM for problematic websites

### ISSUE THREAD

**Issue by rkzack** [ournews/extensions#78]
Hi @webcolor-in we'd like the browser extensions to add a large orange (#fe8e00) warning label at the top of the DOM for problematic websites, per the mockup image below.  

The way this would work is that the extension should send a `?publink` call to our API for every URL the user visits. If the results json array includes the field `verified` and if its set to be `Problematic`, then display the orange label.

The exact words to display are in the `verifiedhelp` field, and the link to link users to is constructed simply from the `pid` field, ie. if the result json array returns pid `162` then the link would be:  `https://our.news/publisher/?pid=162`

The url for the caution image is:  `https://img.our.news/img/caution.png`

<img width="1174" alt="extension-caution-label copy" src="https://user-images.githubusercontent.com/35204816/93093204-67692180-f66e-11ea-916c-f58acabe4b68.png">

**Comment by webcolor-in** [comment]
My estimate: 15 hours

**Comment by rkzack** [comment]
Ok we can proceed up to a max 10 hours on this project. If that works please proceed.

**Comment by webcolor-in** [comment]
Agreed

**Comment by webcolor-in** [comment]
![image](https://user-images.githubusercontent.com/55145799/93467651-93ed9980-f90b-11ea-89ba-be2660d5fdf0.png)
Here is how it looks like

**Comment by webcolor-in** [comment]
Pushed to - satya-2020-09-16
