### ISSUE TITLE
Only open the Join page on first browser install, not on subsequent updates

### ISSUE THREAD

**Issue by rkzack** [ournews/extensions#81]
Hi @webcolor-in at present, the browser extensions load this below URL in a new tab when the extension is first installed:

```https://our.news/join/?extension=2&ffi=0&CID=ON.Firefox``` -- for Firefox
```https://our.news/join/?extension=2&ffi=0&CID=ON.Chrome``` -- for Chrome

However, it also seems to open whenever there's an update. We'd like to stop that, and change the behavior so that it only opens those URLs the first time it is installed, and not on each subsequent update. Is that possible?

**Comment by webcolor-in** [comment]
Done! Have pushed to branch `satya-feb-2021-02-04`

**Comment by rkzack** [comment]
This looks like it will work but I'm unsure how to test. Will take it live and monitor for a few weeks. Thanks!
