### ISSUE TITLE
Login/Register link broken in Chrome extension

### ISSUE THREAD

**Issue by rkzack** [ournews/extensions#82]
Hi @webcolor-in in the Chrome extension, the Login/Register button is broken (see below screenshot). This popup appears within the extension if you're not already logged in, and if you try to "Add Article" on any piece of content.

Could you please fix so that the Login/Register button here opens this url in a new tab:  

```https://our.news/wp-login.php```

<img width="393" alt="Screen Shot 2021-02-03 at 11 38 37 AM" src="https://user-images.githubusercontent.com/35204816/106779121-ad6e5400-6614-11eb-963f-566c1852b726.png">

**Comment by webcolor-in** [comment]
This is because of change from your end - https://github.com/ournews/extensions/commit/0608d290fe72544a9c703431014bf42ff3e4be29

**Comment by rkzack** [comment]
Thanks, yes that was an attempt to fix the problem, as a change to Chrome now makes it impossible for our system to authenticate within an iframe. Now we need the login screen to open in a new tab.  Can you please fix?  Thank you.

**Comment by webcolor-in** [comment]
Pushed in branch `satya-feb-2021-02-04`

**Comment by rkzack** [comment]
This is working well, thank you. Closing issue.
