### ISSUE TITLE
Expand warning label within DOM for problematic articles

### ISSUE THREAD

**Issue by rkzack** [ournews/extensions#85]
Hi @webcolor-in, we'd like to expand the efforts you started in issue #78 where a warning label is added within the DOM for problematic articles. As a next step, we'd like the browser extension to check for an additional field called `indicators`, and if that field exists, display the same warning label, but with slightly modified text. Here's the logic:

1) First to note, one difference from issue #78, we previously changed the API endpoint from `?puburl` to `?probcheck` 

2) If the `indicators` field exists in the `?probcheck` call, display a new warning label that says:

This content has been fact checked. Click to view.

3) The link href value underneath 'Click to View' will come from the `indicators.url` field

4) Here's an example URL to use for testing:

`https://biohackinfo.com/news-bill-gates-id2020-vaccine-implant-covid-19-digital-certificates`

5) If both the `indicators` field and the `verified==problematic` fields exist, we still only want one warning label to be displayed, so in that case the `indicators` field/warning label should take precedence

**Comment by webcolor-in** [comment]
Understood, I am accessing `https://biohackinfo.com/news-bill-gates-id2020-vaccine-implant-covid-19-digital-certificates` but the response does not have `indicators`

```
{pid: "19770", name: "Biohackinfo", url: "biohackinfo.com", image: "", facebook: "",…}
allsides: "Not Rated"
allsidesurl: "https://www.allsides.com/media-bias/media-bias-ratings?utm_source=Live+Partner+Network&utm_medium=Media+Bias+Ratings&utm_campaign=Newstrition"
claimapproved: "0"
claimedby: 0
description: "Self-described as "#Biohacking News: Bodyhacking, DIYbio, genetic engineering, CRISPR, neurohacks, cyborg culture, cybernetic implants, transhumanism, He Jiankui, SciComm.""
facebook: ""
hqlocation: "Undisclosed"
image: ""
knowntype: "888"
launchdate: "unknown."
name: "Biohackinfo"
ownedby: "Owner unknown."
pid: "19770"
totalratings: "1"
totaluserratings: "23"
twitter: "https://twitter.com/biohackinfo"
typedesc: "Caution: Problematic publisher. Learn why."
typehelp: "https://our.news/publisher/?pid=19770"
url: "biohackinfo.com"
verified: "Problematic"
verifiedhelp: "Caution: Problematic publisher. Learn why."
wikipedia: ""
```

**Comment by rkzack** [comment]
Hi @webcolor-in please use this exact API url for testing:

```https://data.our.news/api/?probcheck=https://biohackinfo.com/news-bill-gates-id2020-vaccine-implant-covid-19-digital-certificates```

If you have a trailing slash "/" or trailing characters it will fail. This is just for testing.

**Comment by webcolor-in** [comment]
Updated https://github.com/ournews/extensions/commit/919e4557e6c8525300fc18ca770fcd1161c20983

**Comment by webcolor-in** [comment]
![Uploading image.png…]()

**Comment by webcolor-in** [comment]
Reg URL format - The extension sends current site URL so if it has '/' at the end the extension does not alter and sends as is so maybe we have to allow this? the extra '&' thing is to avoid caching of ajax response on client side.

**Comment by rkzack** [comment]
This is all working good so far, thank you. Will keep testing and let you know any issues.

**Comment by rkzack** [comment]
Hi @webcolor-in this is working well. One change-- can you adjust so that if the user clicks on "Click to view" it opens the extension for this article (as if they clicked the icon) instead of redirecting them to the URL?

**Comment by webcolor-in** [comment]
Yes, this is done and code pushed in same branch.

**Comment by rkzack** [comment]
Working good thank you! Closing issue
