### ISSUE TITLE
Add flag for language

### ISSUE THREAD

**Issue by rkzack** [ournews/extensions#87]
Hi @webcolor-in could you please adjust ALL the extension API calls to append `"&lang=en"` to the end of each call?  We are getting ready to add multi-language support and this is the first step, that will tell our API which language to use. Thanks!

**Comment by webcolor-in** [comment]
Done, have pushed to branch - satya-mar-2021-03-19

**Comment by rkzack** [comment]
Hi @webcolor-in thanks, after testing this seems to work well for GET requests but all POST requests are now broken. Could you please change this so that it only appends &lang=en to GET requests, and not to POSTs?

**Comment by webcolor-in** [comment]
Done, git pushed

**Comment by rkzack** [comment]
This is working now, thanks! Closing issue
